-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  mer. 10 juin 2020 à 15:59
-- Version du serveur :  10.4.10-MariaDB
-- Version de PHP :  7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `ftf`
--

-- --------------------------------------------------------

--
-- Structure de la table `countries`
--

DROP TABLE IF EXISTS `countries`;
CREATE TABLE IF NOT EXISTS `countries` (
  `pays` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `polygone` text COLLATE utf8_unicode_ci NOT NULL,
  `flag` text COLLATE utf8_unicode_ci NOT NULL,
  `code` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `description` text COLLATE utf8_unicode_ci NOT NULL,
  `images` text COLLATE utf8_unicode_ci NOT NULL,
  `points` int(2) NOT NULL,
  `continent` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `indice` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`pays`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Déchargement des données de la table `countries`
--

INSERT INTO `countries` (`pays`, `polygone`, `flag`, `code`, `description`, `images`, `points`, `continent`, `indice`) VALUES
('Afrique Du Sud', '../model/countries/data/zaf.geo.json', '../model/countries/data/zaf.svg', 'zaf', 'L\'Afrique du Sud (en anglais : South Africa ; en afrikaans : Suid-Afrika), aussi nommée République d\'Afrique du Sud1 ou République sud-africaine, est un pays d\'Afrique qui possède la terre la plus au sud de ce continent : le cap de Bonne Espérance, situé à côté de la ville du Cap. Le pays dispose de 3 capitales : la capitale administrative est Pretoria, la capitale législative est Le Cap et la capitale judiciaire est Bloemfontein. Sa plus grande ville est Johannesburg, le cœur économique du pays. Un autre pays est totalement enclavé dans son territoire: le Lesotho.', '../model/pictures/Afrique Du Sud', 10, 'Afrique', 'Sud'),
('Algérie', '../model/countries/data/dza.geo.json', '../model/countries/data/dza.svg', 'DZA', 'L\'Algérie (en arabe : الجزائر), en forme longue et officielle la République algérienne démocratique populaire, est un pays d\'Afrique du Nord situé en bordure de la mer Méditerranée. Sa capitale est Alger. C\'est le pays le plus étendu d\'Afrique, du monde arabe et du bassin méditerranéen.\\nL\'Algérie se situe dans le Maghreb, en Afrique du Nord. Elle est bordée au nord par la mer Méditerranée et 80 % de son territoire est constitué par le désert du Sahara au sud. Les 20 % restants sont principalement formés par la chaîne montagneuse de l\'Atlas, couverte d\'une végétation naturelle et de cultures méditerranéennes qui poussent grâce au climat en vigueur.', '../model/pictures/Algérie/', 5, 'Afrique', 'L\'Algérie est l\'un des plus grand pays d\'Afrique'),
('Allemagne', '../model/countries/data/deu.geo.json', '../model/countries/data/deu.svg', 'DEU', 'L\'Allemagne (en allemand : Deutschland), en forme longue République fédérale d\'Allemagne est l\'un des principaux pays de l\'Europe de l\'Ouest, ainsi que l\'un des membres de l\'Union européenne et de la zone euro.\\nSa capitale est Berlin et sa langue officielle est l\'allemand.\\nL\'Allemagne compte 83 millions d\'habitants en 2018.\\nSa fête nationale est le « Tag der Deutschen Einheit » (jour de l\'unité allemande). C\'est le 3 octobre.\\nL\'Allemagne est une république fédérale. Le pays est divisé en Länder1, des États régionaux très autonomes. Il en existe seize, dont cinq situés dans l\'ancienne Allemagne de l\'Est.\r\n', '../model/pictures/Allemagne', 5, 'Europe', 'Audi'),
('Arabie Saoudite', '../model/countries/data/SAU.geo.json', '../model/countries/data/SAU.svg', 'SAU', 'L\'Arabie saoudite (ou plus rarement Arabie séoudite ; en arabe : العربية السعودية), aussi nommée Royaume d\'Arabie saoudite1, est le plus grand des pays de la péninsule Arabique. Il est bordé par la mer Rouge et le golfe Persique et a des frontières communes avec de nombreux pays comme l\'Irak, le Yémen ou encore l\'Oman. Sa capitale et plus grande ville est Riyad.  Chaque année, le pèlerinage de La Mecque attire des millions de musulmans venus du monde entier.', '../model/pictures/Arabie Saoudite', 10, 'Asie', 'La mer Rouge et le golfe Persique'),
('Argentine', '../model/countries/data/ARG.geo.json', '../model/countries/data/ARG.svg', 'ARG', 'L\'Argentine (forme courante ; en espagnol : Argentina) ou République argentine (forme officielle) est un pays d\'Amérique du Sud. Sa capitale est Buenos Aires. Ses habitants sont les Argentins. On trouve quelques célébrités, comme en football (Diego Armando Maradona, Lionel Messi). Son président actuel est Alberto Fernández.  L\'Argentine est divisée administrativement en 24 provinces dirigées par un gouverneur.', '../model/pictures/Argentine', 15, 'Amérique', 'Messi'),
('Arménie', '../model/countries/data/ARM.geo.json', '../model/countries/data/ARM.svg', 'ARM', 'L\'Arménie (forme courante ; en arménien : Հայաստան) ou République d\'Arménie (forme officielle) est un pays situé à cheval sur l\'Europe et l\'Asie, plus précisément dans le Caucase, entre la Turquie et l\'Iran ; mais est considérée comme faisant partie de l\'Europe géographique. Sa capitale est Erevan, sa langue est l\'arménien, la monnaie est le dram. En 2007, elle comptait 2 971 650 habitants et son actuel président est Armen Sarkissian, qui a succédé en 2018 à Serge Sargsian.', '../model/pictures/Arménie', 20, 'Asie', 'Frontière avec la Turquie.'),
('Australie', '../model/countries/data/AUS.geo.json', '../model/countries/data/AUS.svg', 'AUS', 'L\'Australie (forme courante ; en anglais : Australia), ou Commonwealth d’Australie (forme officielle), est un État fédéral situé en Océanie, qui comprend :  l\'Australie proprement dite, considérée comme la plus grande île du monde ou un continent à elle seule (on parle parfois d\'« île-continent ») ; la Tasmanie ; d\'autres îles de l\'océan Indien, de la mer de Corail ou de l\'océan Austral ; un grand territoire antarctique. Sa capitale est Canberra. La langue officielle est l\'anglais. La monnaie officielle est le dollar australien et sa devise est Avance, belle et juste Australie. C\'est un pays très riche.', '../model/pictures/Australie', 10, 'Océanie', 'Sydney'),
('Belgique', '../model/countries/data/BEL.geo.json', '../model/countries/data/BEL.svg', 'BEL', 'La Belgique (en néerlandais : België, en allemand : Belgien), ou Royaume de Belgique, est un pays d\'Europe ayant une frontière commune avec les Pays-Bas au nord, l\'Allemagne et le Luxembourg à l\'est, la France au sud-ouest, et limitée par la côte de la mer du Nord au nord-ouest.  Ses habitants sont les Belges, sa capitale est Bruxelles et trois langues officielles y sont parlées : le français en Wallonie, le néerlandais en Flandre et l\'allemand dans la Communauté Germanophone de Belgique. La région de Bruxelles-Capitale est officiellement bilingue, mais c\'est une enclave majoritairement francophone dans la région flamande.', '../model/pictures/Belgique', 15, 'Europe', 'Benelux'),
('Brésil', '../model/countries/data/BRA.geo.json', '../model/countries/data/BRA.svg', 'BRA', 'Le Brésil (en portugais : Brasil) est un immense État fédéral de l\'Amérique du Sud avec une superficie de 8 514 877 km² et 190 000 000 habitants. C\'est le cinquième pays du monde pour la superficie et la population. Sa langue officielle est le portugais.', '../model/pictures/Brésil', 15, 'Amérique', 'Berceau du Football'),
('Canada', '../model/countries/data/CAN.geo.json', '../model/countries/data/CAN.svg', 'CAN', 'Le Canada est un pays d\'Amérique du Nord. Il est le deuxième plus grand pays du monde après la Russie. Ottawa est sa capitale située dans la province d\'Ontario. C\'est un pays où il y a le climat continental : il fait très chaud l\'été et il fait très froid l\'hiver. Les personnes qui habitent au Canada s\'appellent des Canadiens (et des Canadiennes).  Il est limité par l\'océan Atlantique, l\'océan Arctique et l\'océan Pacifique. Au sud et à l\'ouest, il y a les États-Unis d\'Amérique. Les deux langues officielles sont le français (le Québec est la seule province à être en majorité francophone) et l\'anglais. Le Canada comporte quatre principales métropoles : Toronto, Montréal, Vancouver et Calgary.', '../model/pictures/Canada', 5, 'Amérique', 'Amérique du Nord '),
('Chili', '../model/countries/data/CHL.geo.json', '../model/countries/data/CHL.svg', 'CHL', 'Le Chili (en espagnol : Chile), ou la République du Chili (nom officiel) est un pays d\'Amérique du Sud, entouré par le Pérou, la Bolivie et l’Argentine. Sa capitale et plus grande ville est Santiago du Chili. La langue du Chili est l\'espagnol et la monnaie nationale le peso. Le Chili est peuplé de plus de 17,3 millions d\'habitants : les Chiliens et les Chiliennes.', '../model/pictures/Chili', 15, 'Amérique', 'Amérique du Nord '),
('Chine', '../model/countries/data/CHN.geo.json', '../model/countries/data/CHN.svg', 'CHN', 'La Chine (en mandarin : 中国), officiellement nommée la République populaire de Chine, est un État situé en Asie dont la capitale est Beijing (Pékin). Troisième pays par la superficie avec 9 596 960 km², c\'est le pays le plus peuplé au monde avec 1,4 milliard d\'habitants. La langue officielle est le chinois mandarin. La Chine est devenue l\'une des plus grandes puissances de la planète.', '../model/pictures/Chine', 10, 'Asie', 'Asie de l’est'),
('Colombie', '../model/countries/data/COL.geo.json', '../model/countries/data/COL.svg', 'COL', 'La Colombie est un pays d\'Amérique du Sud. Il doit son nom à Christophe Colomb, découvreur de l\'Amérique. Il a été colonisé au XVIe siècle par les Espagnols, il est situé immédiatement au sud de l\'Amérique centrale.  La capitale de la Colombie est Bogota.', '../model/pictures/Colombie', 15, 'Amérique', 'Extrême nord du continent sud-américain'),
('Corée du Sud', '../model/countries/data/KOR.geo.json', '../model/countries/data/KOR.svg', 'KOR', 'La Corée du Sud (en coréen : 한국, Hanguk), en forme longue République de Corée (en coréen : 대한민국, Daehan Minguk), est un pays de l\'est de l\'Asie dont la population est de 47,8 millions d\'habitants1. Sa capitale, Séoul, compte près de 11 millions d\'habitants. Située au sud de la péninsule de Corée, elle fait partie des pays développés. Le drapeau national est connu sous le nom de Taegeukgi.', '../model/pictures/Corée du Sud', 20, 'Asie', 'Asie de l\'Est'),
('Côte d\'Ivoire', '../model/countries/data/CIV.geo.json', '../model/countries/data/CIV.svg', 'CIV', 'La Côte d’Ivoire est un pays d\'Afrique occidentale. Sa capitale, Yamoussoukro, est située au centre du pays. Elle est bordée au sud par l’océan Atlantique au niveau du golfe de Guinée, elle partage également des frontières terrestres avec le Liberia et la Guinée à l’ouest, le Mali et le Burkina au nord puis par le Ghana à l’est.  La Côte d´Ivoire, dans ses frontières actuelles, résulte de la colonisation française et est devenue indépendante en 1960. C´est un jeune État, mais l´histoire de ses populations remonte bien plus loin dans le temps. Aujourd\'hui encore, les différentes identités africaines priment sur le sentiment national. La notion d´État a été introduite par les colonisateurs français. L\'unité nationale repose sur les structures coloniales et notamment la langue française', '../model/pictures/Côte D\'ivoire', 15, 'Afrique', 'A coté du Mali '),
('Cuba', '../model/countries/data/CUB.geo.json', '../model/countries/data/CUB.svg', 'CUB', 'Cuba est un pays formé d\'une grande île des Antilles, située entre les États-Unis et l\'Amérique centrale. Sa capitale est La Havane.  Cuba est une ancienne colonie espagnole, indépendante depuis 1868.', '../model/pictures/Cuba', 20, 'Amérique', 'Caraïbes'),
('Égypte', '../model/countries/data/EGY.geo.json', '../model/countries/data/EGY.svg', 'EGY', 'L\'Égypte (en arabe : مصر) est un pays situé au nord-est de l\'Afrique, irrigué par le Nil et célèbre pour ses pyramides, construites du temps des pharaons. Ce pays compte 92 millions d\'habitants, dont 16 millions résident au Caire, la capitale.  En 2008, l\'Égypte a accueilli 14 millions de visiteurs. Le tourisme a représenté 11,1 % du PIB, employant 12 % de la population active', '../model/pictures/Égypte', 15, 'Afrique', 'Pyramides'),
('Émirats Arabes Unis', '../model/countries/data/ARE.geo.json', '../model/countries/data/ARE.svg', 'ARE', 'Les Émirats arabes unis (UAE ; en arabe : دولة الإمارات العربية المتحدة) forment un petit pays d\'Asie de l\'Ouest (83 600 km2), situé sur la péninsule Arabique. Ils sont nés en 1971 à l\'issue du regroupement de 7 émirats : Dubaï, Abou Dabi, Chardja, Fudjayra, Adjman, Umm al-Qaywayn et Ras al-Khayma. La capitale est Abou Dabi (1,4 million d\'habitants) mais l\'une des villes les plus dynamiques est Dubaï (1,2 millions d\'habitants) où se trouve la plus haute tour du monde. Le climat est désertique. Le plus haut sommet est le Jabal Yibir (1 527 mètres d\'altitude). Le pays dispose d\'importantes réserves de pétrole et de gaz naturel qu\'il exporte. Le développement économique attire une main-d\'œuvre étrangère qui travaille dans l\'industrie et le bâtiment. La population est de 4,5 millions d\'habitants, surtout composés d\'immigrés.', '../model/pictures/Émirats Arabes Unis', 15, 'Asie', 'Dubai'),
('États-Unis', '../model/countries/data/usa.geo.json', '../model/countries/data/usa.svg', 'USA', 'Les États-Unis (forme courte et courante ; en anglais : United States), ou États-Unis d\'Amérique (forme longue, en anglais United States of America / « USA »), sont un pays regroupant cinquante États et un district (c\'est un État fédéral, comme l\'Allemagne). Quarante-huit de ces cinquante États sont situés au sud du Canada et au nord du Mexique. L\'Alaska est située à l\'ouest du Canada. Hawaï est dans l\'océan Pacifique. La capitale est Washington DC et les habitants, appelés Américains depuis le xxe siècle, sont parfois appelés États-Uniens . Les États-Unis sont une grande puissance politique, militaire, économique et culturelle. La monnaie est le dollar et la langue la plus parlée l\'anglais.\r\n', '../model/pictures/États-Unis/', 5, 'Amérique', 'Puissance mondiale'),
('Fidji', '../model/countries/data/FJI.geo.json', '../model/countries/data/FJI.svg', 'FJI', 'Les (îles) Fidji ou Fiji (en anglais : Fiji ; en fidjien : Viti ; en hindi des Fidji : फ़िजी) sont un archipel de 322 îles de l’océan Pacifique sud, situé à l’est des îles Vanuatu, à l’ouest des îles Tonga et au sud des îles Tuvalu. Elles forment un État dont le nom officiel est République des Îles Fidji. Leur capitale est Suva.', '../model/pictures/Fidji', 20, 'Océanie', 'Pacifique Sud'),
('France', '../model/countries/data/fra.geo.json', '../model/countries/data/fra.svg', 'FRA', 'La France, ou la République française (nom officiel), est un pays situé à l\'ouest du continent européen. Elle a également des territoires sur tous les autres continents (sauf en Asie) : Saint-Pierre-et-Miquelon, Clipperton, Saint-Martin, Saint-Barthélemy, la Guadeloupe, la Martinique et la Guyane en Amérique, Mayotte et La Réunion en Afrique, la Polynésie française, la Nouvelle-Calédonie et Wallis-et-Futuna en Océanie, quelques îles et îlots inhabités dans l\'océan Indien et un territoire en Antarctique, la Terre Adélie. Son territoire s\'étend sur plus de 640 000 km² dont 120 000 en Outre-mer. Sa capitale est Paris.\r\n', '../model/pictures/France', 5, 'Europe', 'Frommage et vin'),
('Indonésie', '../model/countries/data/IDN.geo.json', '../model/countries/data/IDN.svg', 'IDN', 'L\'Indonésie (forme courte ; en indonésien : Indonesia) ou République d\'Indonésie (forme longue) est un pays dont le territoire est en partie en Asie et en Océanie, mais traditionnellement considéré comme un pays de l\'Asie du Sud-Est. Il s\'étend sur un archipel de plusieurs centaines d\'îles, dont les principales sont Sumatra et Java. Sa capitale est Jakarta (au nord de Java) et ses habitants les Indonésiens.  En 2006, elle comptait 234 693 997 habitants. C\'est le pays possédant la plus grande population musulmane et le quatrième pays le plus peuplé du monde. Les volcans y sont nombreux et les séismes fréquents.', '../model/pictures/Indonésie', 15, 'Asie', 'Asie du Sud-Est'),
('Italie', '../model/countries/data/Ita.geo.json', '../model/countries/data/Ita.svg', 'Ita', 'L\'Italie (en italien : Italia) est un pays de l\'Europe du Sud-Ouest, membre fondateur de l’Union européenne. Sa capitale est Rome, qui est aussi la plus grande ville d\'Italie, mais la plus grande aire urbaine est celle de Milan. Elle fait partie de la zone euro, c\'est-à-dire que sa monnaie est l\'euro. Avant l\'euro, la monnaie italienne était la lire. Sa superficie totale est d\'environ 300 000 km2 et sa population est d\'environ 60 millions d\'habitants (dans la seconde moitié du xixe siècle et la première moitié du xxe siècle des millions d\'Italiens ont émigré vers la France, les États-Unis, l\'Amérique du Nord et du Sud, l\'Australie, la Nouvelle-Zélande). L\'Italie est le 5ème pays le plus dense de l\'union européenne avec 205 hab/km². Parmi ses nombreuses villes, Naples, Turin, Milan, Florence, et Venise.', '../model/pictures/Italie', 15, 'Europe', 'A coté de la France'),
('Japon', '../model/countries/data/JPN.geo.json', '../model/countries/data/JPN.svg', 'JPN', 'Le Japon (en japonais : 日本) est un pays asiatique au large de la Chine et de la Corée dont la capitale est Tokyo. L\'archipel japonais couvre 370 000 km². Le Japon est aussi appelé « pays du soleil levant », parce qu\'il se trouve sur un archipel à l\'Est du continent asiatique. Pays montagneux, le Japon renferme de très nombreux volcans et est régulièrement secoué par des séismes. Ses habitants sont les Japonais, qui sont environ 127 millions. La natalité étant très faible et l\'immigration quasi inexistante, la population japonaise commence à diminuer. Très grand pays industriel, le Japon est l\'un des États les plus riches et les plus développés du monde, il appartient d\'ailleurs à l\'organisation G7. Il possède la plus grande dette du monde ; mais elle est détenue en très grande partie par les Japonais.', '../model/pictures/Japon', 15, 'Asie', 'Océan Pacifique'),
('Madagascar', '../model/countries/data/MDG.geo.json', '../model/countries/data/MDG.svg', 'MDG', 'Madagascar (en malgache : Madagasikara) est un pays formé par une île d\'Afrique située au large (environ 400 kilomètres) du Mozambique, dans l\'océan Indien. Les habitants sont les Malgaches et la monnaie est l\'Ariary. En 2020, la population est de 27 millions d\'habitants environ, qui se répartissent sur 587 000 km² 1. Le pays compte de nombreuses ethnies issues de mélanges successifs de population venant des îles indonésiennes et d\'Afrique, puis plus tard d\'Inde, de Chine et d\'Europe.', '../model/pictures/Madagascar', 15, 'Afrique', 'A coté de l\'Afrique du Sud'),
('Maroc', '../model/countries/data/MAR.geo.json', '../model/countries/data/MAR.svg', 'MAR', 'Le Maroc (en arabe : al-Maġrib « المغرب »,parfois nommé al-Marrok « المروك », en berbère : Imeġrib « ⵍⵎⵖⵔⵉⴱ », Amerrok« ⴰⵎⵔⵔⵓⴽ »), est un royaume situé en Afrique, plus précisément en Afrique du Nord. Le nom Maroc vient du nom de l\'ancienne capitale du pays Marrakech (Amurakuc, diminutif de Amur n Akuc, signifiant en langue berbère \"Terre de Dieu\"). Le Maroc est le seul pays qui ait accès à la fois à la mer Méditerranée et à l\'océan Atlantique. La capitale est Rabat et la monnaie est le dirham marocain.', '../model/pictures/Maroc', 10, 'Afrique', 'Maghreb'),
('Norvège', '../model/countries/data/NOR.geo.json', '../model/countries/data/NOR.svg', 'NOR', 'La Norvège (en bokmål : Norge ; en nynorsk : Noreg), officiellement nommée le Royaume de Norvège, est un pays qui fait partie de l\'Europe (au sens géographique du terme) et de la Scandinavie. Cepandant, elle ne fait pas partie de l\'Union européenne (qui est une union politique et économique dont font partis beaucoup de pays européens).  La Norvège est peuplée de 5,3 millions d\'habitants, ce qui est faible au vu de sa superficie. La densité de population est de 13,8 habitants au km² ; par comparaison, en France métropolitaine, ce taux est de 114 habitants au km² mais il ne faut pas oublier qu\'une grande partie du nord de la Norvège est inhabitée à cause du grand froid.', '../model/pictures/Norvège', 20, 'Europe', 'Au Nord '),
('Nouvelle-Zélande', '../model/countries/data/NZL.geo.json', '../model/countries/data/NZL.svg', 'NZL', 'La Nouvelle-Zélande (en anglais : New Zealand ; en māori : Aotearoa) est un pays situé au sud de l\'océan Pacifique, à environ 2 000 km de l\'Australie. Le pays est très isolé géographiquement.  C\'est un groupe de deux îles complètement à l\'autre bout de la planète par rapport à l\'Europe ; il y a environ 12 heures de décalage horaire. Sa capitale est Wellington mais sa plus grande ville est Auckland.  La Nouvelle-Zélande est un pays très développé et prospère.', '../model/pictures/Nouvelle-Zélande', 15, 'Océanie', 'Sud-ouest de l\'océan Pacifique'),
('Papouasie-Nouvelle-Guinée', '../model/countries/data/PNG.geo.json', '../model/countries/data/PNG.svg', 'PNG', 'La Papouasie-Nouvelle-Guinée (en anglais : Papua New Guinea) est un des plus grands pays de l\'Océanie, c\'est aussi l\'un des plus pauvres. Il est situé au nord de l\'Australie et à l\'est de l\'Indonésie occupant la partie orientale de l\'île de Nouvelle-Guinée et plusieurs îles alentour. La capitale est Port Moresby.', '../model/pictures/Papouasie-Nouvelle-Guinée', 15, 'Océanie', 'Sud-ouest de l\'océan Pacifique'),
('Pays-Bas', '../model/countries/data/NLD.geo.json', '../model/countries/data/NLD.svg', 'NLD', 'Les Pays-Bas, (en néerlandais : Nederland), ou bien, en forme longue, Royaume des Pays-Bas (en néerlandais : Koninkrijk der Nederlanden) sont un État d\'Europe du Nord limité à l\'est par l\'Allemagne, au sud par la Belgique et au nord par la mer du Nord. La superficie des Pays-Bas est de 41 528 km², soit l\'équivalent de la Suisse.', '../model/pictures/Pays-Bas', 15, 'Europe', 'Benelux'),
('Pologne', '../model/countries/data/POL.geo.json', '../model/countries/data/POL.svg', 'POL', 'La Pologne (en polonais : Polska) est un pays à l\'est de l\'Europe, membre de l\'Union européenne depuis le 1er mai 2004.  Sa capitale est Varsovie. Les autres grandes villes (plus de 250 000 habitants) sont Cracovie, Łódź, Wrocław, Poznań, Gdańsk, Szczecin, Bydgoszcz, Lublin, Katowice, Białystok, Gdynia, Częstochowa.', '../model/pictures/Pologne', 15, 'Europe', 'A coté de l\'Allemagne'),
('Royaume-Uni', '../model/countries/data/GBR.geo.json', '../model/countries/data/GBR.svg', 'GBR', 'Le Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord, appelé également Royaume-Uni (en anglais : United Kingdom), est un État européen qui comprend l\'Angleterre, l\'Écosse, le Pays de Galles (soit la Grande-Bretagne) et l\'Irlande du Nord.  Sa capitale et plus grande ville est Londres.  Le Royaume-Uni fait partie du Commonwealth.', '../model/pictures/Royaume-Uni', 10, 'Europe', 'Brexit'),
('Russie', '../model/countries/data/rus.geo.json', '../model/countries/data/rus.svg', 'RUS', 'La Russie (forme courante ; en russe : Россия) ou Fédération de Russie (forme officielle) est le plus vaste État du monde, qui a pour particularité de s\'étendre sur deux continents, pour un quart l\'Europe (où se trouve sa capitale Moscou) et pour les trois quarts l\'Asie. Cependant, il est traditionnellement considéré que la Russie est un pays européen (d\'ailleurs, 78 % de sa population vit dans la partie européenne).\\nLa Russie est membre fondateur de la Communauté des États indépendants (CEI), membre permanent du Conseil de sécurité des Nations unies, ainsi que membre du G8 et du Conseil de l\'Europe.\\nIl y avait 146,9 millions de Russes en 2018. Le pays est une république fédérale dirigée par un président.\\nLes habitants de la Russie sont appelés les Russes.\r\n', '../model/pictures/Russie', 5, 'Asie', 'Kremlin'),
('Sénégal', '../model/countries/data/SEN.geo.json', '../model/countries/data/SEN.svg', 'SEN', 'Le Sénégal (nom courant), ou République du Sénégal (nom officiel), est un pays d\'Afrique de l\'Ouest. La superficie est de 196 722 km2. Il compte plus de 16 millions d\'habitants en 2019.  La capitale est Dakar.  Son président se nomme Macky Sall. La date de son indépendance est le 4 avril. Son héros national est Lat-Dior Ngoné Latyr Diop.', '../model/pictures/Sénégal', 15, 'Afrique', 'Afrique de l\'ouest '),
('Suède', '../model/countries/data/SWE.geo.json', '../model/countries/data/SWE.svg', 'SWE', 'La Suède (en suédois : Sverige) est un pays de l\'Union européenne, situé au nord de la mer Baltique. Ses habitants s\'appellent les Suédois. Sa langue officielle est le suédois.', '../model/pictures/Suède', 15, 'Europe', 'Nord'),
('Suisse', '../model/countries/data/che.geo.json', '../model/countries/data/che.svg', 'CHE', 'La Suisse (en allemand : Schweiz ; en italien : Svizzera ; en romanche : Svizra) est un pays d\'Europe ayant une frontière commune avec l\'Allemagne, la France, l\'Italie, l\'Autriche et le Liechtenstein.\r\nSes habitants sont les Suisses et les Suissesses, sa capitale est Berne, et il y a quatre langues officielles : le français, l\'allemand, l\'italien et le romanche.\r\nLa Suisse a une superficie de 41 285 km², et une population de 8 139 600 hab. soit une densité de 188,6 hab./km².\r\nLa monnaie suisse est le franc suisse, car le pays ne fait partie ni de l\'Union européenne, ni de la zone euro.\r\nLa Suisse est un État fédéral, formée depuis 1848 de 26 cantons. La fête nationale est le 1er août.\r\nLes principales villes sont Zurich, Genève, Bâle, Lausanne et Berne.\r\nLa Suisse ne fait pas partie de l\'Union européenne mais elle a passé des accords avec l\'UE et fait notamment partie de l\'espace Schengen. La Suisse est cependant membre d\'une autre organisation régionale qui est le Conseil de l\'Europe.', '', 10, 'Europe', 'Grande banques'),
('Tanzanie', '../model/countries/data/TZA.geo.json', '../model/countries/data/TZA.svg', 'TZA', 'La Tanzanie (en anglais et en kiswahili : Tanzania) est un pays d\'Afrique de l\'Est situé en bordure de l\'océan Indien. Sa capitale est Dodoma, mais la plus grande ville du pays est Dar es Salam. La Tanzanie est l\'union de deux territoires distincts qui existaient de manière séparée avant la décolonisation : le Tanganyika et Zanzibar.', '../model/pictures/Tanzanie', 20, 'Afrique', 'A coté du Madagascar'),
('Thaïlande', '../model/countries/data/THA.geo.json', '../model/countries/data/THA.svg', 'THA', 'La Thaïlande ou le Royaume de Thaïlande (forme longue ; en thaï : ประเทศไทย) est un pays d\'Asie du Sud-Est dont les pays frontaliers sont la Birmanie, le Laos, le Cambodge et la Malaisie. Au sud, il est délimité par le golfe de Thaïlande. Le pays compte environ 68 millions d\'habitants1 pour une superficie de 514 000 km². Sa capitale et sa plus grande ville est Bangkok.', '../model/pictures/Thaïlande', 20, 'Asie', 'Asie du Sud-Est'),
('Tunisie', '../model/countries/data/TUN.geo.json', '../model/countries/data/TUN.svg', 'TUN', 'La Tunisie (en arabe : تونس / Tūnis) est un pays d\'Afrique du Nord situé à l\'ouest de la Libye et à l\'est de l\'Algérie. Elle couvre 163 610 km2, ce qui en fait le plus petit pays du Maghreb mais l\'un des premiers à être devenu indépendant. Sa capitale est Tunis et sa monnaie est le dinar tunisien. indice maghreb ', '../model/pictures/Tunisie', 10, 'Afrique', 'Maghreb'),
('Turquie', '../model/countries/data/TUR.geo.json', '../model/countries/data/TUR.svg', 'TUR', 'La Turquie (en turc : Türkiye) est un pays dont la plus grande partie du territoire (96 % côté est) est située en Asie. Le reste (4 % côté ouest) est située en Europe mais qui représente 14 % de sa population, soit plus de 14.5 millions de personnes. Aussi le pays est-il traditionnellement considéré comme un pays d\'Asie.', '../model/pictures/Turquie', 15, 'Asie', 'Istanbul'),
('Uruguay', '../model/countries/data/URY.geo.json', '../model/countries/data/URY.svg', 'URY', 'L’Uruguay est un pays de l\'Amérique du Sud. Il s\'appelle officiellement République orientale de l\'Uruguay et doit son nom à un fleuve : le rio Uruguay. Ses habitants s\'appellent les Uruguayens et les Uruguayennes. Montevideo en est la capitale administrative et économique, ainsi que le principal port. C\'est l\'un des plus petits pays d\'Amérique du Sud.', '../model/pictures/Uruguay', 15, 'Amérique', 'Amérique du Sud'),
('Zimbabwe', '../model/countries/data/ZWE.geo.json', '../model/countries/data/ZWE.svg', 'ZWE', 'Le Zimbabwe est un État d\'Afrique australe de 390 000 km2. Sa capitale est Harare, on y parle officiellement l\'anglais et la monnaie nationale est le dollar du Zimbabwe.', '../model/pictures/Zimbabwe', 20, 'Afrique', 'Sud');

-- --------------------------------------------------------

--
-- Structure de la table `partie`
--

DROP TABLE IF EXISTS `partie`;
CREATE TABLE IF NOT EXISTS `partie` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `date` date NOT NULL,
  `score` int(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `pseudo` (`pseudo`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Déchargement des données de la table `partie`
--

INSERT INTO `partie` (`id`, `pseudo`, `date`, `score`) VALUES
(20, 'admin', '2020-06-10', 45),
(21, 'admin', '2020-06-10', 5);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `pseudo` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `nom` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `pass` varchar(300) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`pseudo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`pseudo`, `nom`, `email`, `pass`) VALUES
('admin', 'admin', 'admin@admin.fr', '$2y$12$aiOGT8hEGCcfqVyBT92ca.25j6ov0.Eqw039BKpisKkCH8QUCIjyG');

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `partie`
--
ALTER TABLE `partie`
  ADD CONSTRAINT `fk_pseudo` FOREIGN KEY (`pseudo`) REFERENCES `users` (`pseudo`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
